EQUIPMENT_PROMPTS = [
    "a leg press machine",
    "a treadmill",
    "an elliptical",
    "a stationary bike",
    "a cable machine",
    "a smith machine",
    "a pull-up bar",
    "a chest press machine",
    "a shoulder press machine",
    "a lat pulldown machine",
    "a leg extension machine",
    "a leg curl machine",
    "a hip abductor machine",
    "a rowing machine",
    "a stair climber",
    "a pec deck machine",
    "a preacher curl bench",
    "a triceps pushdown machine",
    "an ab crunch machine",
    "a back extension machine",
    "a dip station",
    "dumbbells",
    "a barbell",
    "kettlebells",
    "resistance bands",
    "a medicine ball",
    "battle ropes",
    "a punching bag"
]