"""Add step tracking tables

Revision ID: 7af81fab8e73
Revises: 
Create Date: 2026-01-21 13:49:55.973293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af81fab8e73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('calories_per_100g', sa.Float(precision=8, asdecimal=2), nullable=False),
    sa.Column('protein_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('carbs_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('fat_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('fiber_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('sugar_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('sodium_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('cholesterol_mg', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('saturated_fat_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('trans_fat_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('vitamin_a_mcg', sa.Float(precision=8, asdecimal=2), nullable=True),
    sa.Column('vitamin_c_mg', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('calcium_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('iron_mg', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('potassium_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('daily_step_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_flights', sa.Integer(), nullable=False),
    sa.Column('step_goal', sa.Integer(), nullable=False),
    sa.Column('goal_progress', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_goal_achieved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_step_summaries_id'), 'daily_step_summaries', ['id'], unique=False)
    op.create_table('food_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_calories', sa.Float(precision=8, asdecimal=2), nullable=False),
    sa.Column('total_protein_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('total_carbs_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('total_fat_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('total_fiber_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('total_sugar_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('total_sodium_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(precision=3, asdecimal=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_scans_id'), 'food_scans', ['id'], unique=False)
    op.create_index(op.f('ix_food_scans_scan_date'), 'food_scans', ['scan_date'], unique=False)
    op.create_index(op.f('ix_food_scans_user_id'), 'food_scans', ['user_id'], unique=False)
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_goal', sa.Float(precision=8, asdecimal=2), nullable=True),
    sa.Column('protein_goal_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('carbs_goal_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('fat_goal_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('fiber_goal_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('sodium_limit_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_goals_date'), 'nutrition_goals', ['date'], unique=False)
    op.create_index(op.f('ix_nutrition_goals_id'), 'nutrition_goals', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=False)
    op.create_table('step_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('step_goal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_goals_id'), 'step_goals', ['id'], unique=False)
    op.create_table('step_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('distance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('flights', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_history_id'), 'step_history', ['id'], unique=False)
    op.create_table('food_scan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(precision=8, asdecimal=2), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('calories', sa.Float(precision=8, asdecimal=2), nullable=False),
    sa.Column('protein_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('carbs_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('fat_g', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('fiber_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('sugar_g', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('sodium_mg', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['food_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_scan_items_food_item_id'), 'food_scan_items', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_food_scan_items_id'), 'food_scan_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_scan_items_scan_id'), 'food_scan_items', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_scan_items_scan_id'), table_name='food_scan_items')
    op.drop_index(op.f('ix_food_scan_items_id'), table_name='food_scan_items')
    op.drop_index(op.f('ix_food_scan_items_food_item_id'), table_name='food_scan_items')
    op.drop_table('food_scan_items')
    op.drop_index(op.f('ix_step_history_id'), table_name='step_history')
    op.drop_table('step_history')
    op.drop_index(op.f('ix_step_goals_id'), table_name='step_goals')
    op.drop_table('step_goals')
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.drop_index(op.f('ix_nutrition_goals_id'), table_name='nutrition_goals')
    op.drop_index(op.f('ix_nutrition_goals_date'), table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    op.drop_index(op.f('ix_food_scans_user_id'), table_name='food_scans')
    op.drop_index(op.f('ix_food_scans_scan_date'), table_name='food_scans')
    op.drop_index(op.f('ix_food_scans_id'), table_name='food_scans')
    op.drop_table('food_scans')
    op.drop_index(op.f('ix_daily_step_summaries_id'), table_name='daily_step_summaries')
    op.drop_table('daily_step_summaries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
